MODEL:
    graph: './models/resnet50_v1b/IR_fused_for_CModel_graph.json'
    params: './models/resnet50_v1b/IR_fused_for_CModel_params.npz'
QUAN:
    strategy: 'symmetry_max_t' # minmax, null, scale_shift, symmetry_max
    # strategy: 'null' # minmax, null, scale_shift, symmetry_max
    qconfig:
        weight_quan: 'perlayer' # perchannel , perlayer
        table: 'calibrations/resnet50_v1b.json'
        image_path: './models/images'
        # image_path: '../tools/images/'
EVALUATION:
    input_images: './models/image_for_compare'
    label_file: 'models/imagenet_lsvrc_2015_synsets.txt'
    image_file: 'models/imagenet_5000test.list'
    input_node: '0:0'
    output_node: '506:0'
SAVE_PATH: 'pbs/resnet50_v1b_quan.pb'
